const infoData = [{"id":9,"name":"村子加","itemIndex":6,"opacity":100,"visible":true,"bounds":{"left":26,"top":51,"right":453,"bottom":243,"width":427,"height":192},"typename":"LayerSet","width":427,"height":192,"children":[{"id":8,"name":"房子-加-1","itemIndex":5,"opacity":100,"visible":true,"bounds":{"left":308,"top":55,"right":453,"bottom":206,"width":145,"height":151,"relativeLeft":282,"relativeTop":4,"relativeRight":0,"relativeBottom":37,"percentageLeft":66.04,"percentageRight":0,"percentageTop":2.08,"percentageBottom":19.27,"percentageHeight":78.64,"percentageWidth":33.95},"typename":"ArtLayer","width":145,"height":151,"kind":"NORMAL","isBackgroundLayer":false,"fileName":"房子-加-1.png"},{"id":6,"name":"房子-加-2","itemIndex":4,"opacity":100,"visible":true,"bounds":{"left":37,"top":51,"right":450,"bottom":243,"width":413,"height":192,"relativeLeft":11,"relativeTop":0,"relativeRight":3,"relativeBottom":0,"percentageLeft":2.57,"percentageRight":0.7,"percentageTop":0,"percentageBottom":0,"percentageHeight":100,"percentageWidth":96.72},"typename":"ArtLayer","width":413,"height":192,"kind":"NORMAL","isBackgroundLayer":false,"fileName":"房子-加-2.png"},{"id":4,"name":"房子-加-3","itemIndex":3,"opacity":100,"visible":true,"bounds":{"left":26,"top":131,"right":124,"bottom":194,"width":98,"height":63,"relativeLeft":0,"relativeTop":80,"relativeRight":329,"relativeBottom":49,"percentageLeft":0,"percentageRight":77.04,"percentageTop":41.66,"percentageBottom":25.52,"percentageHeight":32.81,"percentageWidth":22.95},"typename":"ArtLayer","width":98,"height":63,"kind":"NORMAL","isBackgroundLayer":false,"fileName":"房子-加-3.png"}]}]
let newData = []
let index = 0
let data = ''
// console.log(infoData)
infoData[0].children.forEach(element => {
  data += `{name: '${element.name}',fileName: '${element.fileName}',width: ${element.width * 1.5},height: ${element.height * 1.5},opacity: ${element.opacity},left: ${element.bounds.left},top: ${element.bounds.top},index: ${element.index + 150}},
  `
})

console.log(data)